learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE URLs
app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('user_login/', views.user_login, name='user_login')
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views
urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logoutsdddsdsfdsfdsfsddsdfa/', views.user_logout, name='user_logout'),
    path('special_page/', views.special_page, name='special_page'),

]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional parameters
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    # profile_pics should be a subdirectory in the media folder.
    # for images, pillow is installed by default in Django.

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model  = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

# imports for LOGIN
from django.contrib.auth import authenticate, login, logout
# from django.core.urlresolvers import reverse
from django.urls import  reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special_page(request):
    return HttpResponse('you are logged in, nice!')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            #Here, we are hashing the password fieled of the User, and saving that in the database.
            user.set_password(user.password)
            user.save()

            #We use commit = Flase, so that the profile form does not try to override the user.
            profile = profile_form.save(commit = False)
            profile.user = user # This is the main line that ensures only one instance of each user is present.
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic'] # This simply ensures that we get the profile pic that django has stored inside request

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)


    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/register.html', {'user_form':user_form,
                                                           'profile_form':profile_form,
                                                           'registered':registered})

# never call your view login, as you are importing login above, and then it will be overriden.
def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # User is automatically authenticated by this one single line
        user = authenticate(username=username, password=password)

        if user:
            #check paranthesis afet is_active
            if user.is_active:
                login(request, user)
                # if they have logged in successfully, reverse them and redirect them back to home page.
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE!')
        else:
            print('Someone tried to log in and failed.')
            print('username: ' + username + ' and password: ' + password)
            return HttpResponse('Invalid login details supplied.')
    else:

        return render(request, 'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>
      {% block title_block %}
      {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
        <p>Hi {{ user.username }}, hope you're doing good</p>
        {% else %}
        <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
        <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
        {% endif  %}

      </div>
    </div>
  </div>
</nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}

{% block title_block %}
HOME PAGE
{% endblock %}

{% block body_block %}
<div class="jumbotron">
  <h1>DJANGO LEVEL FIVE!</h1>
</div>
{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
  <div class="container">
    <h1>Please Log In : </h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username: </label>
      <input type="text" name="username" placeholder="Enter Username">
      <label for="password">Password: </label>
      <input type="password" name="password">

      <input type="submit" value="Log In!">
    </form>

  </div>
{% endblock %}

learning_users/templates/basic_app/register.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block title_block %}
REGISTER
{% endblock %}

{% block body_block %}
<div class="container" style="background-color:grey; padding:5px; border-radius: 20px;">
  {% if registered %}
    <h1>Thank You for registering</h1>
  {% else %}
    <h1>Register Here</h1>
    <h3>Fill out the Form:</h3>
    <form  enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" value="Register!" style="border-radius: 5px">

    </form>
  {% endif %}

</div>
{% endblock %}